name: stalwart

services:
  stalwart:
    image: stalwartlabs/stalwart:v0.16.6
    restart: unless-stopped
    hostname: mail.yoke-th.me
    environment:
      STALWART_RECOVERY_MODE: ${STALWART_RECOVERY_MODE:-false}
      STALWART_RECOVERY_ADMIN: ${STALWART_RECOVERY_ADMIN:-}
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "143:143"
      - "993:993"
      - "4190:4190"
    volumes:
      - stalwart-data:/opt/stalwart
    networks:
      - internal
      - public

volumes:
  stalwart-data:

networks:
  internal:
    name: internal
    external: true
  public:
    name: public
    external: true
