name: stalwart

services:
  stalwart:
    image: stalwartlabs/stalwart:v0.16.6
    restart: unless-stopped
    hostname: mail.yoke-th.me
    environment:
      STALWART_RECOVERY_MODE: ${STALWART_RECOVERY_MODE:-false}
      STALWART_RECOVERY_ADMIN: ${STALWART_RECOVERY_ADMIN:-}
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "143:143"
      - "993:993"
      - "4190:4190"
    volumes:
      - stalwart-data:/opt/stalwart
    networks:
      - internal
      - public
    labels:
      - traefik.enable=true
      - traefik.docker.network=public
      - traefik.http.routers.stalwart.rule=Host(`mail.yoke-th.me`) || Host(`mta-sts.yoke-th.me`) || Host(`autoconfig.yoke-th.me`) || Host(`autodiscover.yoke-th.me`)
      - traefik.http.routers.stalwart.entrypoints=websecure
      - traefik.http.routers.stalwart.tls=true
      - traefik.http.routers.stalwart.tls.certresolver=cloudflare
      - traefik.http.routers.stalwart.tls.domains[0].main=yoke-th.me
      - traefik.http.routers.stalwart.tls.domains[0].sans=*.yoke-th.me
      - traefik.http.services.stalwart.loadbalancer.server.port=8080

volumes:
  stalwart-data:

networks:
  internal:
    name: internal
    external: true
  public:
    name: public
    external: true
